<?php

namespace AppBundle\Repository;

use AppBundle\Entity\AntecedentePatologico;

/**
 * AntecedentePatologicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntecedentePatologicoRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarAntecedentePatologico($data)
    {
        try{
            $em = $this->getEntityManager();
            $antecedentePatologico = new AntecedentePatologico();
            $antecedentePatologico->setNombre($data['nombre']);

            $em->persist($antecedentePatologico);
            $em->flush();
            $msg = $antecedentePatologico;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El antecedente patológico ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el antecedente patológico';
            }
        }

        return $msg;
    }

    public function modificarAntecedentePatologico($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $antecedentePatologico = $em->getRepository('AppBundle:AntecedentePatologico')->find($data['idAntecedentePatologico']);
            $antecedentePatologico->setNombre($data['nombre']);

            $em->persist($antecedentePatologico);
            $em->flush();
            $msg = $antecedentePatologico;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el antecedente patológico';
        }

        return $msg;
    }

    public function eliminarAntecedentePatologico($id)
    {
        try {
            $em = $this->getEntityManager();
            $antecedentePatologico = $em->getRepository('AppBundle:AntecedentePatologico')->find($id);

            $em->remove($antecedentePatologico);
            $em->flush();
            $msg = $antecedentePatologico;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen pacientes asociados a antecedente patológico, no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el antecedente patológico';
            }
        }
        return $msg;
    }
}
