<?php

namespace AppBundle\Repository;
use AppBundle\Entity\CausaFallecimiento;

/**
 * CausaFallecimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CausaFallecimientoRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarCausaFallecimiento($data)
    {
        try{
            $em = $this->getEntityManager();
            $causaFallecimiento = new CausaFallecimiento();
            $causaFallecimiento->setNombre($data['nombre']);

            $em->persist($causaFallecimiento);
            $em->flush();
            $msg = $causaFallecimiento;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La causa de fallecimiento ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la causa de fallecimiento';
            }
        }

        return $msg;
    }

    public function modificarCausaFallecimiento($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $causaFallecimiento = $em->getRepository('AppBundle:CausaFallecimiento')->find($data['idCausaFallecimiento']);
            $causaFallecimiento->setNombre($data['nombre']);

            $em->persist($causaFallecimiento);
            $em->flush();
            $msg = $causaFallecimiento;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar la causa de fallecimiento';
        }

        return $msg;
    }

    public function eliminarCausaFallecimiento($id)
    {
        try {
            $em = $this->getEntityManager();
            $causaFallecimiento = $em->getRepository('AppBundle:CausaFallecimiento')->find($id);

            $em->remove($causaFallecimiento);
            $em->flush();
            $msg = $causaFallecimiento;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen pacientes asociados a esta causa de fallecimiento , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la causa de fallecimiento';
            }
        }
        return $msg;
    }
}
