<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CoinfeccionPaciente;

/**
 * CoinfeccionPacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoinfeccionPacienteRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarCoinfeccionesPaciente($paciente , $coinfecciones)
    {
        try
        {
            $em = $this->getEntityManager();
            foreach ( $coinfecciones as  $enfermedad)
            {
                if($enfermedad != ""){
                    $coinfeccion = $em->getRepository('AppBundle:Coinfeccion')->find($enfermedad['idCoinfeccion']);
                    $coinfeccionPaciente = new CoinfeccionPaciente();
                    $coinfeccionPaciente->setCoinfeccion($coinfeccion);
                    $coinfeccionPaciente->setFecha(new \DateTime($enfermedad['fecha']));
                    $coinfeccionPaciente->setPaciente($paciente);
                    $em->persist($coinfeccionPaciente);
                }
            }
            $em->flush();
            $msg = 'ok';

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al insertar las coinfecciónes del paciente';

        }
        return $msg;
    }
}
