<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Coinfeccion;

/**
 * CoinfeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoinfeccionRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarCoinfeccion($data)
    {
        try{
            $em = $this->getEntityManager();
            $coinfeccion = new Coinfeccion();
            $coinfeccion->setNombre($data['nombre']);

            $em->persist($coinfeccion);
            $em->flush();
            $msg = $coinfeccion;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La coinfección ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la coinfección';
            }
        }

        return $msg;
    }

    public function modificarCoinfeccion($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $coinfeccion = $em->getRepository('AppBundle:Coinfeccion')->find($data['idCoinfeccion']);
            $coinfeccion->setNombre($data['nombre']);

            $em->persist($coinfeccion);
            $em->flush();
            $msg = $coinfeccion;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar la coinfección';
        }

        return $msg;
    }

    public function eliminarCoinfeccion($id)
    {
        try {
            $em = $this->getEntityManager();
            $coinfeccion = $em->getRepository('AppBundle:Coinfeccion')->find($id);

            $em->remove($coinfeccion);
            $em->flush();
            $msg = $coinfeccion;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen pacientes asociados a esta coinfección , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la coinfección';
            }
        }
        return $msg;
    }
}
