<?php

namespace AppBundle\Repository;

/**
 * ColorPielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorPielRepository extends \Doctrine\ORM\EntityRepository
{
}
