<?php

namespace AppBundle\Repository;

use AppBundle\Entity\EstadoCivil;

/**
 * EstadoCivilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoCivilRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarEstadoCivil($data)
    {
        try{
            $em = $this->getEntityManager();
            $estadoCivil = new EstadoCivil();
            $estadoCivil->setNombre($data['nombre']);

            $em->persist($estadoCivil);
            $em->flush();
            $msg = $estadoCivil;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El estado civil ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el estado civil';
            }
        }

        return $msg;
    }

    public function modificarEstadoCivil($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $estadoCivil = $em->getRepository('AppBundle:EstadoCivil')->find($data['idEstadoCivil']);
            $estadoCivil->setNombre($data['nombre']);

            $em->persist($estadoCivil);
            $em->flush();
            $msg = $estadoCivil;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el estado civil';
        }

        return $msg;
    }

    public function eliminarEstadoCivil($id)
    {
        try {
            $em = $this->getEntityManager();
            $estadoCivil = $em->getRepository('AppBundle:EstadoCivil')->find($id);

            $em->remove($estadoCivil);
            $em->flush();
            $msg = $estadoCivil;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen pacientes asociados a este estado civil , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el estado civil';
            }
        }
        return $msg;
    }
}
