<?php

namespace AppBundle\Repository;
use AppBundle\Entity\EvolucionClinica;


/**
 * EvolucionClinicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvolucionClinicaRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarEvolucionClinica($data)
    {
        try{
            $em = $this->getEntityManager();
            $evolucionClinica = new EvolucionClinica();
            $evolucionClinica->setNombre($data['nombre']);


            $em->persist($evolucionClinica);
            $em->flush();
            $msg = $evolucionClinica;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La evolución clínica ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la evolución clínica';
            }
        }

        return $msg;
    }

    public function modificarEvolucionClinica($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $evolucionClinica = $em->getRepository('AppBundle:EvolucionClinica')->find($data['idEvolucionClinica']);
            $evolucionClinica->setNombre($data['nombre']);

            $em->persist($evolucionClinica);
            $em->flush();
            $msg = $evolucionClinica;

        }catch (\Exception $e)
        {
            $msg = 'Error';
        }

        return $msg;
    }

    public function eliminarEvolucionClinica($id)
    {
        try {
            $em = $this->getEntityManager();
            $evolucionClinica = $em->getRepository('AppBundle:EvolucionClinica')->find($id);

            $em->remove($evolucionClinica);
            $em->flush();
            $msg = $evolucionClinica;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen motivos asociados a esta evolución clínica , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la evolución clínica';
            }
        }
        return $msg;
    }
}
