<?php

namespace AppBundle\Repository;
use AppBundle\Entity\FormaInfeccion;

/**
 * FormaInfeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormaInfeccionRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarFormaInfeccion($data)
    {
        try{
            $em = $this->getEntityManager();
            $formaInfeccion = new FormaInfeccion();
            $formaInfeccion->setNombre($data['nombre']);

            $em->persist($formaInfeccion);
            $em->flush();
            $msg = $formaInfeccion;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La forma de infeccion ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la forma de infeccion';
            }
        }

        return $msg;
    }

    public function modificarFormaInfeccion($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $formaInfeccion = $em->getRepository('AppBundle:FormaInfeccion')->find($data['idFormaInfeccion']);
            $formaInfeccion->setNombre($data['nombre']);

            $em->persist($formaInfeccion);
            $em->flush();
            $msg = $formaInfeccion;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar la forma de infeccion';
        }

        return $msg;
    }

    public function eliminarFormaInfeccion($id)
    {
        try {
            $em = $this->getEntityManager();
            $formaInfeccion = $em->getRepository('AppBundle:FormaInfeccion')->find($id);

            $em->remove($formaInfeccion);
            $em->flush();
            $msg = $formaInfeccion;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen pacientes asociados a esta forma de infeccion, no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la forma de infeccion';
            }
        }
        return $msg;
    }
}
