<?php

namespace AppBundle\Repository;
use AppBundle\Entity\FuentePesquisa;

/**
 * FuentePesquisaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuentePesquisaRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarFuentePesquisa($data)
    {
        try{
            $em = $this->getEntityManager();
            $fuentePesquisa = new FuentePesquisa();
            $fuentePesquisa->setNombre($data['nombre']);

            $em->persist($fuentePesquisa);
            $em->flush();
            $msg = $fuentePesquisa;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La fuente de pesquisa ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la fuente pesquisa';
            }
        }

        return $msg;
    }

    public function modificarFuentePesquisa($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $fuentePesquisa = $em->getRepository('AppBundle:FuentePesquisa')->find($data['idFuentePesquisa']);
            $fuentePesquisa->setNombre($data['nombre']);

            $em->persist($fuentePesquisa);
            $em->flush();
            $msg = $fuentePesquisa;

        }catch (\Exception $e)
        {
            $msg = 'Error';
        }

        return $msg;
    }

    public function eliminarFuentePesquisa($id)
    {
        try {
            $em = $this->getEntityManager();
            $fuentePesquisa = $em->getRepository('AppBundle:FuentePesquisa')->find($id);

            $em->remove($fuentePesquisa);
            $em->flush();
            $msg = $fuentePesquisa;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen motivos asociados a esta fuente de pesquisa , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la fuente de pesquisa';
            }
        }
        return $msg;
    }
}
