<?php

namespace AppBundle\Repository;

use AppBundle\Entity\HijoVacuna;

/**
 * HijoVacunaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HijoVacunaRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarVacunas($hijoVacunas , $hijos)
    {
        try{
            $em = $this->getEntityManager();
            foreach ($hijoVacunas as $hijoVacuna)
            {
                if($hijoVacuna != '')
                {
                    $vacuna = new HijoVacuna();
                    $vacuna->setFechaVacunaPrimera(new \DateTime($hijoVacuna['vacunaPrimera']));
                    if ($hijoVacuna['vacunaSegunda'] !='') {
                        $vacuna->setFechaVacunaSegunda(new \DateTime($hijoVacuna['vacunaSegunda']));
                    }
                    if ($hijoVacuna['vacunaTercera'] !='') {
                        $vacuna->setFechaVacunaTercera(new \DateTime($hijoVacuna['vacunaTercera']));
                    }
                    if ($hijoVacuna['reactivacion'] !='') {
                        $vacuna->setFechaReactivacion(new \DateTime($hijoVacuna['reactivacion']));
                    }

                    $vacuna->setGestanteHijo($hijos);
                    $em->persist($vacuna);
                }
            }
            $em->flush();
            $msg = 'ok';

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al insertar las vacunas';
        }

        return $msg;
    }

    public function modificarVacunas($hijoVacunas , $hijos)
    {
        try{
            $em = $this->getEntityManager();
            $misVacunas = $hijos->getHijoVacunas();
            foreach ($misVacunas as $vacuna)
            {
                $hijos->removeHijoVacuna($vacuna);
                $em->persist($hijos);
                $em->remove($vacuna);
            }

            foreach ($hijoVacunas as $hijoVacuna)
            {
                if($hijoVacuna != '')
                {
                    $vacuna = new HijoVacuna();
                    $vacuna->setFechaVacunaPrimera(new \DateTime($hijoVacuna['vacunaPrimera']));
                    if ($hijoVacuna['vacunaSegunda'] !='') {
                        $vacuna->setFechaVacunaSegunda(new \DateTime($hijoVacuna['vacunaSegunda']));
                    }
                    if ($hijoVacuna['vacunaTercera'] !='') {
                        $vacuna->setFechaVacunaTercera(new \DateTime($hijoVacuna['vacunaTercera']));
                    }
                    if ($hijoVacuna['reactivacion'] !='') {
                        $vacuna->setFechaReactivacion(new \DateTime($hijoVacuna['reactivacion']));
                    }

                    $vacuna->setGestanteHijo($hijos);
                    $em->persist($vacuna);
                }
            }
            $em->flush();
            $msg = 'ok';

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar las vacunas';
        }

        return $msg;
    }
}
