<?php

namespace AppBundle\Repository;

use AppBundle\Entity\HijoPrueba;

/**
 * HijoPruebaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HijoPruebaRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarPruebas($hijoPruebas , $hijos)
    {
        try{
            $em = $this->getEntityManager();
            foreach ($hijoPruebas as $hijoPrueba)
            {
                if($hijoPrueba != "")
                {
                    $prueba = new HijoPrueba();
                    $prueba->setFecha(new \DateTime($hijoPrueba['fechaPrueba']));
                    $nombrePrueba = $em->getRepository('AppBundle:Prueba')->find($hijoPrueba['prueba']);
                    $prueba->setPrueba($nombrePrueba);
                    $resultado = $em->getRepository('AppBundle:ResultadoPrueba')->find($hijoPrueba['resultado']);
                    $prueba->setResultadoPrueba($resultado);

                    if ($hijoPrueba['valor'] !='') {
                        $prueba->setValor($hijoPrueba['valor']);
                    }

                    $prueba->setGestanteHijo($hijos);
                    $em->persist($prueba);
                }
            }
            $em->flush();
            $msg = 'ok';

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al insertar las pruebas ';
        }

        return $msg;
    }

    public function modificarPruebas($hijoPruebas , $hijos)
    {
        try{
            $em = $this->getEntityManager();
            $misPruebas = $hijos->getHijoPruebas();
            foreach ($misPruebas as $prueba)
            {
                $hijos->removeHijoPrueba($prueba);
                $em->persist($hijos);
                $em->remove($prueba);
            }

            foreach ($hijoPruebas as $hijoPrueba)
            {
                if($hijoPrueba != "")
                {
                    $prueba = new HijoPrueba();
                    $prueba->setFecha(new \DateTime($hijoPrueba['fechaPrueba']));
                    $nombrePrueba = $em->getRepository('AppBundle:Prueba')->find($hijoPrueba['prueba']);
                    $prueba->setPrueba($nombrePrueba);
                    $resultado = $em->getRepository('AppBundle:ResultadoPrueba')->find($hijoPrueba['resultado']);
                    $prueba->setResultadoPrueba($resultado);

                    if ($hijoPrueba['valor'] !='') {
                        $prueba->setValor($hijoPrueba['valor']);
                    }

                    $prueba->setGestanteHijo($hijos);
                    $em->persist($prueba);
                }
            }
            $em->flush();
            $msg = 'ok';

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar las pruebas ';
        }

        return $msg;
    }
}
