<?php

namespace AppBundle\Repository;

use AppBundle\Entity\NivelEscolaridad;

/**
 * NivelEscolaridadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelEscolaridadRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarNivelEscolaridad($data)
    {
        try{
            $em = $this->getEntityManager();
            $nivelEscolaridad = new NivelEscolaridad();
            $nivelEscolaridad->setNombre($data['nombre']);

            $em->persist($nivelEscolaridad);
            $em->flush();
            $msg = $nivelEscolaridad;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El nivel de escolaridad ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el nivel de escolaridad';
            }
        }

        return $msg;
    }

    public function modificarNivelEscolaridad($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $nivelEscolaridad = $em->getRepository('AppBundle:NivelEscolaridad')->find($data['idNivelEscolaridad']);
            $nivelEscolaridad->setNombre($data['nombre']);

            $em->persist($nivelEscolaridad);
            $em->flush();
            $msg = $nivelEscolaridad;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el nivel de escolaridad';
        }

        return $msg;
    }

    public function eliminarNivelEscolaridad($id)
    {
        try {
            $em = $this->getEntityManager();
            $nivelEscolaridad = $em->getRepository('AppBundle:NivelEscolaridad')->find($id);

            $em->remove($nivelEscolaridad);
            $em->flush();
            $msg = $nivelEscolaridad;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen pacientes asociados a este nivel de escolaridad , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el nivel de escolaridad';
            }
        }
        return $msg;
    }
}
