<?php

namespace AppBundle\Repository;

use AppBundle\Entity\PacienteEsquemaMedicamento;

/**
 * PacienteEsquemaMedicamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacienteEsquemaMedicamentoRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarEsquemasMedicamentos($esquemas , $paciente)
    {
        try{
            $em = $this->getEntityManager();
            foreach ($esquemas as $esquema)
            {
                if($esquema != "")
                {
                    $esquemaMedicamento = new PacienteEsquemaMedicamento();
                    $esquemaMedicamento->setFechaInicio(new \DateTime($esquema['fechaInicioTratamiento']));
                    if ($esquema['fechaFinalTratamiento'] !=''){
                        $esquemaMedicamento->setFechaFinal(new \DateTime($esquema['fechaFinalTratamiento']));
                    }
                    $esquemaMedicamento->setPaciente($paciente);
                    $medicamentos = $esquema['medicamentos'];
                    foreach ($medicamentos as $idMedicamento)
                    {
                        $medicamento = $em->getRepository('AppBundle:Medicamento')->find($idMedicamento);
                        $esquemaMedicamento->addMedicamento($medicamento);
                    }
                    $em->persist($esquemaMedicamento);
                }
            }
            $em->flush();
            $msg = 'ok';

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al insertar los esquemas de medicamentos';
        }

        return $msg;
    }

    public function modificarEsquemasMedicamentos($esquemas , $paciente ,$user)
    {
        $em = $this->getEntityManager();
        try{
            $misEsquemas = $paciente->getMedicamentoEsquemas();
            foreach ($misEsquemas as $esquema)
            {
                $paciente->removeMedicamentoEsquema($esquema);
                $em->remove($esquema);
            }

            foreach ($esquemas as $esquema)
            {
                if($esquema != ""){
                    $esquemaMedicamento = new PacienteEsquemaMedicamento();
                    $esquemaMedicamento->setFechaInicio(new \DateTime($esquema['fechaInicioTratamiento']));
                    if ($esquema['fechaFinalTratamiento'] !=''){
                        $esquemaMedicamento->setFechaFinal(new \DateTime($esquema['fechaFinalTratamiento']));
                    }
                    $esquemaMedicamento->setPaciente($paciente);
                    $medicamentos = $esquema['medicamentos'];
                    foreach ($medicamentos as $idMedicamento)
                    {
                        $medicamento = $em->getRepository('AppBundle:Medicamento')->find($idMedicamento);
                        $esquemaMedicamento->addMedicamento($medicamento);
                    }
                    $em->persist($esquemaMedicamento);
                }
            }
            $em->persist($paciente);
            $dataTraza = array(
                'username' => $user->getUsername(),
                'nombre' => $user->getNombre(),
                'operacion' => 'Modificar tratamiento del paciente',
                'descripcion' => 'Se modificó el tratamiento del paciente: '.$paciente->getNombre().' '.$paciente->getPrimerApellido().' '.$paciente->getSegundoApellido().' y carnet '.$paciente->getCarnetIdentidad(),
            );

            $em->getRepository('AppBundle:Traza')-> guardarTraza($dataTraza);
            $em->flush();
            $msg = 'ok';

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar los esquemas de medicamentos';
        }

        return $msg;
    }
}
