<?php

namespace AppBundle\Repository;

use AppBundle\Entity\PacientePrueba;

/**
 * PacientePruebaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacientePruebaRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarPruebas($pacientePruebas , $paciente)
    {
        try{
            $em = $this->getEntityManager();
            foreach ($pacientePruebas as $pacientePrueba)
            {
                if($pacientePrueba != "")
                {
                    $prueba = new PacientePrueba();
                    $prueba->setFecha(new \DateTime($pacientePrueba['fechaPrueba']));
                    $nombrePrueba = $em->getRepository('AppBundle:Prueba')->find($pacientePrueba['prueba']);
                    $prueba->setPrueba($nombrePrueba);
                    $resultado = $em->getRepository('AppBundle:ResultadoPrueba')->find($pacientePrueba['resultado']);
                    $prueba->setResultadoPrueba($resultado);

                    if ($pacientePrueba['valor'] !='') {
                        $prueba->setValor($pacientePrueba['valor']);
                    }

                    $prueba->setPaciente($paciente);
                    $em->persist($prueba);
                }
            }
            $em->flush();
            $msg = 'ok';

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al insertar las pruebas ';
        }

        return $msg;
    }

    public function modificarPruebas($pacientePruebas , $paciente ,$user)
    {
        try{
            $em = $this->getEntityManager();
            $misPruebas = $paciente->getPacientePruebas();
            foreach ($misPruebas as $prueba)
            {
                $paciente->removePacientePrueba($prueba);
                $em->remove($prueba);
            }

            foreach ($pacientePruebas as $pacientePrueba)
            {
                if($pacientePrueba != ""){
                    $prueba = new PacientePrueba();
                    $prueba->setFecha(new \DateTime($pacientePrueba['fechaPrueba']));
                    $nombrePrueba = $em->getRepository('AppBundle:Prueba')->find($pacientePrueba['prueba']);
                    $prueba->setPrueba($nombrePrueba);
                    $resultado = $em->getRepository('AppBundle:ResultadoPrueba')->find($pacientePrueba['resultado']);
                    $prueba->setResultadoPrueba($resultado);

                    if ($pacientePrueba['valor'] !='') {
                        $prueba->setValor($pacientePrueba['valor']);
                    }
                    $em->persist($prueba);
                    $prueba->setPaciente($paciente);
                }
            }
            $em->persist($paciente);

            $dataTraza = array(
                'username' => $user->getUsername(),
                'nombre' => $user->getNombre(),
                'operacion' => 'Modificar pruebas del paciente',
                'descripcion' => 'Se modificaron las pruebas del paciente: '.$paciente->getNombre().' '.$paciente->getPrimerApellido().' '.$paciente->getSegundoApellido().' y carnet '.$paciente->getCarnetIdentidad(),
            );
            $em->getRepository('AppBundle:Traza')-> guardarTraza($dataTraza);

            $em->flush();
            $msg = 'ok';

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar las pruebas ';
        }

        return $msg;
    }
}
