<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Provincia;

/**
 * ProvinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinciaRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarProvincia($data)
    {
        try{
            $em = $this->getEntityManager();
            $provincia = new Provincia();
            $provincia->setNombre($data['nombre']);
            $provincia->setCodigo($data['codigo']);

            $em->persist($provincia);
            $em->flush();
            $msg = $provincia;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La provincia ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la provincia';
            }
        }

        return $msg;
    }

    public function modificarProvincia($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $provincia = $em->getRepository('AppBundle:Provincia')->find($data['idProvincia']);
            $provincia->setNombre($data['nombre']);

            $em->persist($provincia);
            $em->flush();
            $msg = $provincia;

        }catch (\Exception $e)
        {
            $msg = 'Error';
        }

        return $msg;
    }

    public function eliminarProvincia($id)
    {
        try {
            $em = $this->getEntityManager();
            $provincia = $em->getRepository('AppBundle:Provincia')->find($id);

            $em->remove($provincia);
            $em->flush();
            $msg = $provincia;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen municipios asociados a esta provincia , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la provincia';
            }
        }
        return $msg;
    }
}
