<?php

namespace AppBundle\Repository;

/**
 * TipoEtiologiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEtiologiaRepository extends \Doctrine\ORM\EntityRepository
{
}
