<?php

namespace AppBundle\Repository;

use AppBundle\Entity\TipoHepatitis;

/**
 * TipoHepatitisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoHepatitisRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarTipoHepatitis($data)
    {
        try{
            $em = $this->getEntityManager();
            $tipoHepatitis = new TipoHepatitis();
            $tipoHepatitis->setNombre($data['nombre']);

            $em->persist($tipoHepatitis);
            $em->flush();
            $msg = $tipoHepatitis;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El tipo de hepatitis ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el tipo de hepatitis';
            }
        }

        return $msg;
    }

    public function modificarTipoHepatitis($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $tipoHepatitis = $em->getRepository('AppBundle:TipoHepatitis')->find($data['idTipoHepatitis']);
            $tipoHepatitis->setNombre($data['nombre']);

            $em->persist($tipoHepatitis);
            $em->flush();
            $msg = $tipoHepatitis;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el tipo de hepatitis';
        }

        return $msg;
    }

    public function eliminarTipoHepatitis($id)
    {
        try {
            $em = $this->getEntityManager();
            $tipoHepatitis = $em->getRepository('AppBundle:TipoHepatitis')->find($id);

            $em->remove($tipoHepatitis);
            $em->flush();
            $msg = $tipoHepatitis;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen seguimientos asociados a este tipo de hepatitis , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el tipo de hepatitis';
            }
        }
        return $msg;
    }
}
