<?php

namespace AppBundle\Repository;

use AppBundle\Entity\TotalPoblacion;

/**
 * TotalPoblacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TotalPoblacionRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarTotalPoblacion($data)
    {
        try{
            $em = $this->getEntityManager();
            $totalPoblacion = new TotalPoblacion();
            $totalPoblacion->setYear($data['year']);
            $totalPoblacion->setTotal($data['total']);
            $totalPoblacion->setTotalFemenino($data['totalFemenino']);
            $totalPoblacion->setTotalMasculino($data['totalMasculino']);

            $em->persist($totalPoblacion);
            $em->flush();
            $msg = $totalPoblacion;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El total de población ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el total de población';
            }
        }

        return $msg;
    }

    public function modificarTotalPoblacion($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $totalPoblacion = $em->getRepository('AppBundle:TotalPoblacion')->find($data['idTotalPoblacion']);
            $totalPoblacion->setYear($data['year']);
            $totalPoblacion->setTotal($data['total']);
            $totalPoblacion->setTotalFemenino($data['totalFemenino']);
            $totalPoblacion->setTotalMasculino($data['totalMasculino']);

            $em->persist($totalPoblacion);
            $em->flush();
            $msg = $totalPoblacion;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error el total de población';
        }

        return $msg;
    }

    public function eliminarTotalPoblacion($id)
    {
        try {
            $em = $this->getEntityManager();
            $totalPoblacion = $em->getRepository('AppBundle:TotalPoblacion')->find($id);

            $em->remove($totalPoblacion);
            $em->flush();
            $msg = $totalPoblacion;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen información asociada a este total de población , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el total de población';
            }
        }
        return $msg;
    }

    public function graficoTotalPoblacionYearActual($year)
    {

        $em = $this->getEntityManager();

        $dql = 'SELECT p.total as total
                FROM AppBundle:TotalPoblacion p
                WHERE p.year = :p1';

        $query = $em->createQuery($dql);
        $query->setParameter('p1', $year);

        return $query->getResult();

    }

    public function graficoTotalPoblacionYearSexo($year,$sexo)
    {

        $em = $this->getEntityManager();

        if ($sexo === 'Femenino') {
            $dql = 'SELECT p.totalFemenino as total
                FROM AppBundle:TotalPoblacion p
                WHERE p.year = :p1';
        }else {
            $dql = 'SELECT p.totalMasculino as total
                FROM AppBundle:TotalPoblacion p
                WHERE p.year = :p1';
        }

        $query = $em->createQuery($dql);
        $query->setParameter('p1', $year);

        return $query->getResult();

    }

}
