<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Vacuna;

/**
 * VacunaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacunaRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarVacuna($data)
    {
        try{
            $em = $this->getEntityManager();
            $vacuna = new Vacuna();
            $vacuna->setNombre($data['nombre']);

            $em->persist($vacuna);
            $em->flush();
            $msg = $vacuna;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La vacuna ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la vacuna';
            }
        }

        return $msg;
    }

    public function modificarVacuna($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $vacuna = $em->getRepository('AppBundle:Vacuna')->find($data['idVacuna']);
            $vacuna->setNombre($data['nombre']);

            $em->persist($vacuna);
            $em->flush();
            $msg = $vacuna;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar la vacuna';
        }

        return $msg;
    }

    public function eliminarVacuna($id)
    {
        try {
            $em = $this->getEntityManager();
            $vacuna = $em->getRepository('AppBundle:Vacuna')->find($id);

            $em->remove($vacuna);
            $em->flush();
            $msg = $vacuna;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen pacientes asociados a esta vacuna, no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la vacuna';
            }
        }
        return $msg;
    }
}
